# https://ghfast.top/github.com/AlexxIT/builder/blob/master/builder.sh
name: go2rtc (rockchip)
description: '[老王杂谈说]：为Rockchip进行硬件转码'
url: https://ghfast.top/github.com/AlexxIT/go2rtc
image: alexxit/go2rtc
arch: [aarch64]
# https://developers.home-assistant.io/docs/add-ons/configuration
version: 1.9.11-rockchip
slug: go2rtc-rockchip
init: false
startup: system
host_network: true
homeassistant_api: true
video: true
audio: true
ingress: true
ingress_port: 1984
panel_icon: mdi:camera-wireless
map: ["config:rw", "media", "ssl"]
