name: Sonarr
version: 0.4.3
slug: sonarr
description: '[老王杂谈说]：适合新闻组和比特 torrent 用户的智能 PVR'
url: https://ghfast.top/github.com/hassio-addons/addon-sonarr/tree/main/README.md
webui: http://[HOST]:[PORT:8989]
init: false
arch:
  - aarch64
  - amd64
map:
  - addon_config:rw
  - share:rw
  - media:rw
ports:
  8989/tcp: 8989
image: ghcr.nju.edu.cn/hassio-addons/sonarr/{arch}
