arch:
  - amd64
description: '[老王杂谈说]：Whatshaper for Home Assistant'
image: ghcr.nju.edu.cn/alexbelgium/whatsapper-{arch}
map:
  - addon_config:rw
  - share:rw
name: Whatsapper
options:
  env_vars: []
ports:
  3000/tcp: 4000
ports_description:
  3000/tcp: Api interface
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
slug: whatsapper
udev: true
url: https://ghfast.top/github.com/alexbelgium/hassio-addons/tree/master/whatsapper
version: 1.0.5
