name: Example
version: 12.0.1
slug: example
description: '[老王杂谈说]：社区Home Assistant附加组件的示例附加组件'
url: https://ghfast.top/github.com/hassio-addons/addon-example
init: false
arch:
  - aarch64
  - amd64
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
image: ghcr.nju.edu.cn/hassio-addons/example/{arch}
