name: EMQX
version: 0.8.1
slug: emqx
description: '[老王杂谈说]：最可扩展的开源MQTT代理，适用于物联网，是Mosquitto插件的替代方案。'
url: https://ghfast.top/github.com/hassio-addons/addon-emqx
startup: services
ingress: true
ingress_port: 18083
ingress_stream: true
init: false
panel_icon: mdi:pipe
panel_title: EMQX
arch:
  - aarch64
  - amd64
map:
  - ssl
  - addon_config:rw
options:
  env_vars: []
host_network: true
schema:
  env_vars:
    - name: match(^EMQX_([A-Z0-9_])+$)
      value: str
image: ghcr.nju.edu.cn/hassio-addons/emqx/{arch}
