name: xqrepack
version: 1.7.6
slug: xqrepack
description: '[老王杂谈说]：这些脚本允许你修改小米路由器固件镜像，以确保 SSH 和 UART 访问始终启用。'
url: https://ghfast.top/github.com/FaserF/hassio-addons/tree/master/xqrepack
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - share:rw
init: false
options:
  firmware_path: "/share/miwifi_firmware/"
  firmware_name: miwifi_r3600_firmware.bin
schema:
  firmware_path: str
  firmware_name: str
