name: xqrepack
version: 1.8.1
slug: xqrepack
description: '[老王杂谈说]：这些脚本允许你修改小米路由器的不同固件镜像，以确保SSH和UART访问始终启用。'
url: https://ghfast.top/github.com/FaserF/hassio-addons/tree/master/xqrepack
arch:
  - aarch64
  - amd64
map:
  - share:rw
init: false
options:
  firmware_path: "/share/miwifi_firmware/"
  firmware_name: miwifi_r3600_firmware.bin
schema:
  firmware_path: str
  firmware_name: str
