name: pterodactyl Wings Gameserver
version: 1.5.1
slug: pterodactyl_wings
description: '[老王杂谈说]：开源游戏服务器'
url: https://ghfast.top/github.com/FaserF/hassio-addons/tree/master/pterodactyl-wings
arch:
  - aarch64
  - amd64
image: ghcr.nju.edu.cn/faserf/pterodactyl-wings-{arch}
#webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
map:
  - share:rw
ingress: true
init: false
panel_icon: mdi:controller
options:
  config_file:
schema:
  config_file: str
ports:
  "2022": 2022
  8080/tcp: 8080
ports_description:
  8080/tcp: "8080"
  2022/tcp: "2022"
