name: Prowlarr
version: 0.27.0
slug: prowlarr-0
description: '[老王杂谈说]：基于流行的arr堆栈构建的索引器管理器/代理，以与您的各种PVR应用程序集成'
url: https://ghfast.top/github.com/hassio-addons/addon-prowlarr/tree/main/README.md
webui: http://[HOST]:[PORT:9696]
init: false
arch:
  - aarch64
  - amd64
map:
  - addon_config:rw
  - share:rw
  - media:rw
ports:
  9696/tcp: 9696
image: ghcr.nju.edu.cn/hassio-addons/prowlarr/{arch}
