# https://ghfast.top/github.com/AlexxIT/builder/blob/master/builder.sh
name: go2rtc
description: '[老王杂谈说]：硬件转码：Intel（VAAPI）和Raspberry（V4L2）'
url: https://ghfast.top/github.com/AlexxIT/go2rtc
image: alexxit/go2rtc
arch: [amd64, aarch64, i386, armv7]
# https://developers.home-assistant.io/docs/add-ons/configuration
version: 1.9.12
slug: go2rtc
init: false
startup: system
host_network: true
homeassistant_api: true
video: true
audio: true
ingress: true
ingress_port: 1984
panel_icon: mdi:camera-wireless
map: ["config:rw", "media", "ssl"]
