name: OpenSSL
version: 1.7.2
slug: openssl
description: '[老王杂谈说]：生成自签名证书'
url: https://ghfast.top/github.com/FaserF/hassio-addons/tree/master/openssl
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: ghcr.nju.edu.cn/faserf/openssl-{arch}
map:
  - ssl:rw
init: false
options:
  website_name:
schema:
  website_name: str
