name: AirCast
version: 5.0.2
slug: aircast
description: '[老王杂谈说]：适用于您的Chromecast设备的AirPlay功能。'
url: https://ghfast.top/github.com/hassio-addons/addon-aircast
startup: services
init: false
arch:
  - aarch64
  - amd64
hassio_api: true
host_network: true
map:
  - addon_config:rw
  - homeassistant_config:rw
options:
  latency_rtp: 0
  latency_http: 0
  drift: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  address: str?
  latency_rtp: int
  latency_http: int
  drift: bool
image: ghcr.nju.edu.cn/hassio-addons/aircast/{arch}
