name: Cloudflared
version: 5.3.9
breaking_versions:
  - 5.3.7
slug: cloudflared
description: '[老王杂谈说]：使用 Cloudflare Tunnel 远程连接 Home Assistant 而无需打开任何端口'
url: https://ghfast.top/github.com/brenner-tobias/addon-cloudflared/
codenotary: dev@brenner.tech
startup: services
init: false
hassio_api: true
arch:
  - aarch64
  - amd64
  - armv7
map:
  - addon_config:rw
  - homeassistant_config
options:
  external_hostname: ''
  additional_hosts: []
  use_builtin_proxy: true
ports:
  36500/tcp: null
schema:
  external_hostname: str?
  additional_hosts:
    - hostname: str
      service: str
      disableChunkedEncoding: bool?
  tunnel_name: str?
  catch_all_service: str?
  nginx_proxy_manager: bool?
  use_builtin_proxy: bool?
  tunnel_token: str?
  post_quantum: bool?
  run_parameters:
    - match(^(--edge-bind-address|--edge-ip-version|--grace-period|--ha-connections|--logfile|--loglevel|--pidfile|--protocol|--region|--retries|--tag)=.*$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.nju.edu.cn/brenner-tobias/cloudflared/{arch}
