name: Lidarr
version: 0.14.0
slug: lidarr
description: '[老王杂谈说]：看起来和闻起来像Sonarr，但它是为音乐制作的'
url: https://ghfast.top/github.com/hassio-addons/addon-lidarr/tree/main/README.md
webui: http://[HOST]:[PORT:8686]
init: false
arch:
  - aarch64
  - amd64
map:
  - addon_config:rw
  - share:rw
  - media:rw
ports:
  8686/tcp: 8686
image: ghcr.nju.edu.cn/hassio-addons/lidarr/{arch}
