name: Uptime Kuma
version: 0.15.0
slug: uptime-kuma
description: '[老王杂谈说]：null'
url: https://ghfast.top/github.com/hassio-addons/addon-uptime-kuma
webui: http://[HOST]:[PORT:3001]
init: false
arch:
  - aarch64
  - amd64
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web interface
discovery:
  - uptime_kuma
image: ghcr.nju.edu.cn/hassio-addons/uptime-kuma/{arch}
