name: "GlassHome Dashboard"
version: "0.4.1"
slug: glasshome
description: "[老王杂谈说]：为Home Assistant设计的现代、可定制的拖放式小部件仪表板"
url: "https://ghfast.top/github.com/IhsenBouallegue/glasshome-addon"
arch:
  - amd64
  - aarch64
init: false
ingress: false
panel_icon: mdi:view-dashboard
startup: application
boot: auto
ports:
  3123/tcp: 3123
ports_description:
  3123/tcp: "Web interface"
map:
  - data:rw
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)
image: "ghcr.nju.edu.cn/ihsenbouallegue/{arch}-glasshome"
